### ISSUE TITLE
Bug: Response not successful: Received status code 414

### ISSUE THREAD

**Issue by Muzammil-khan710** [wpengine/faustjs#1484]
I am using headless Wordpress with Faustjs. Right now when I am querying the data it is throwing 414 error. My other queries are working fine but only one [query](https://github.com/Muzammil-khan710/nextjs-wordpress/blob/main/src/wp-templates/singular.tsx) is throwing error 414.

## Applicable Versions

- WordPress version: 6.2.2
- Wpgraphql version: 1.14.6
- NextJs version: 13.1.8
- React version: 18.2.0
- apollo/client version: 3.7.16
- faustwp/blocks version: 1.0.0
- faustwp/cli : 1.0.1
- faustwp/core: 1.0.1

## Steps To Reproduce

1. follow this [guide](https://faustjs.org/tutorial/get-started-with-faust) and create a small repo
2. Add some pages as well as templates
3. Add minimal repo similar to [this ](https://github.com/Muzammil-khan710/nextjs-wordpress).
4. Now go to articles and click any of article's link.

Link to code example: https://github.com/Muzammil-khan710/nextjs-wordpress

## The current behavior

It is throwing 414 error 

## The expected behavior
the query should resolve

**Comment by CesarBenavides777** [comment]
@Muzammil-khan710  I am also getting this while hosting on flywheel. I think there is a config you can tweak to up the request size limit.

**Comment by CesarBenavides777** [comment]
I think it may be a server limitation and not a problem with Faust specifically

**Comment by Muzammil-khan710** [comment]
Hey @blakewilson , I am using Hostinger for hosting wp instance.

**Comment by Muzammil-khan710** [comment]
@blakewilson I have tried solutions as you mentioned second solution my query got resolved without any errors. 
But I would like to go with the first solution as it will be better for our project but when I am applying first solution I am receiving this error `ApolloError: Variable "$id" of type "ID" used in position expecting type "ID!".` 
Can you please help me through it also what approach will be better for us first or second because in future we may add some more queries in our project.

**Comment by blakewilson** [comment]
That was an issue in `1.0.0`. Upgrading to the latest version of Faust (`1.0.2`) should fix that!

**Comment by Muzammil-khan710** [comment]
@blakewilson  I have updated packages but my issue is not resolved.  I am getting 414 error again. Also I have changed my query .

**Comment by blakewilson** [comment]
Hi @Muzammil-khan710, did you implement one of the following steps from this list as well?



> Hi @Muzammil-khan710,
> 
> Thank you for your issue and all relevant information/reproduction, It really helps us! [In 1.0.0 we changed the default WPGraphQL request method from `POST` to `GET`.](https://github.com/wpengine/faustjs/releases/tag/%40faustwp%2Fcore%401.0.0) For most cases, this makes the requests resolve faster, because the requests can be cached. This also means less requests to the actual WordPress database, which can save you from the WP instance going down. However there is a caveat as the query string and variables are concatenated into the URL. In some cases, the URL can become too long based on the size of the query, and the server you are using. There are a few solutions here:
> 
> * [Use persisted queries in Faust](https://faustjs.org/guide/how-to-use-apollo-in-faust) with [WPGraphQL Smart Cache](https://wordpress.org/plugins/wpgraphql-smart-cache/) (this hashes the queries into a consistently sized query ID, so you'll never run into queries being too large). This is the best of both worlds as you are still using `GET` requests for queries but you are no longer susceptible to URLs being too long.
> * Change the WPGraphQL requests back to `POST` requests [using the `useGETForQueries` config toggle in Faust](https://faustjs.org/guide/how-to-use-apollo-in-faust#changing-the-desired-http-method-for-your-graphql-requests)
> * talk to your hosting provider/modify your server to increase the max URL length
> * Decrease the query size by only requesting what is needed, etc.

If so, what did you implement? Updating to the latest should fix the `ApolloError` you encountered with persisted queries, but one of these actions is still required.

**Comment by Muzammil-khan710** [comment]
yes I have added   `usePersistedQueries:true` but still I am receiving 414 error. here is my [repo](https://github.com/Muzammil-khan710/nextjs-wordpress).

Apart from that I am also using sitemap provided by faust. 
I noticed that 'article' is also coming in sitemap but there is no such article/page named as article in my nextjs app as well as wordpress articles(custom post type) here is my sitemap [link](https://nextjs-wordpress-rho-sandy.vercel.app/sitemap.xml?sitemap=article-sitemap.xml) for articles and here is the [sitemap](https://nextjs-wordpress-rho-sandy.vercel.app/sitemap.xml) .

**Comment by theodesp** [comment]
Hello @Muzammil-khan710>

I performed a basic networking request/response test and I got this error message when performing a query for the singular template:

```
 result: '<!DOCTYPE html>\n' +
    '<html style="height:100%">\n' +
    '<head>\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />\n' +
    '<title> 414 Request-URI Too Large\r\n' +
    '</title></head>\n' +
    '<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">\n' +
    '<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">\n' +
    '        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">414</h1>\n' +
    '<h2 style="margin-top:20px;font-size: 30px;">Request-URI Too Large\r\n' +
    '</h2>\n' +
    '<p>The request URL is over the maximum size allowed!</p>\n' +
    '</div></div></body></html>\n'
}
```

This means that your server does impose some limitation withs the  GET request URL size. So I changed the `faust.config` to be `  useGETForQueries: false,` and now it works! 

Please verify on your end that this fixes your issue.

**Comment by theodesp** [comment]
Hey @Muzammil-khan710. I think the `getSitemapProps` creates root paths for your custom post types like `/article`, `/blog`, etc. Isn't it  better to add a new page or path to handle those?

`/pages/article.js` or `/pages/article/index.js`

**Comment by theodesp** [comment]
I actually noticed that your WP site has an `/article` sitepath, so the `getSitemapProps` will include this in the list.

<img width="906" alt="Screenshot 2023-07-14 at 11 46 00" src="https://github.com/wpengine/faustjs/assets/328805/2bab717e-3e19-45b1-9ad9-4eee527915fa">

**Comment by Muzammil-khan710** [comment]
I agree that my WP site has` /article `sitepath but I don't have such page exists in my WP site. Isn't this a bug ? 
As I don't want to include such sitepaths which doesn't exists on WP site.

**Comment by theodesp** [comment]
Hey @Muzammil-khan710 is the sitemaps configured from WP? I mean if you could filter out the invalid `/article` path there there shouldn't be available in Faust. We don't expose that level of filtering yet.

**Comment by Muzammil-khan710** [comment]
There is no path named as article @theodesp 
![Screenshot (350)](https://github.com/wpengine/faustjs/assets/82377076/0c8510ef-6db8-4086-9182-f079577270bd)

**Comment by Muzammil-khan710** [comment]
Hey @theodesp, Was looking in WP for fixing this issue and since I have created this using CPT UI. Where archive was stated as  true. and changing it to false has solved the issue. Now there is no /article sitepath coming on sitemaps. 
Thanks !
you can close this issue now.

**Comment by tuanfront-end** [comment]
> Hi @Muzammil-khan710,
> 
> Thank you for your issue and all relevant information/reproduction, It really helps us! [In 1.0.0 we changed the default WPGraphQL request method from `POST` to `GET`.](https://github.com/wpengine/faustjs/releases/tag/%40faustwp%2Fcore%401.0.0) For most cases, this makes the requests resolve faster, because the requests can be cached. This also means less requests to the actual WordPress database, which can save you from the WP instance going down. However there is a caveat as the query string and variables are concatenated into the URL. In some cases, the URL can become too long based on the size of the query, and the server you are using. There are a few solutions here:
> 
> * [Use persisted queries in Faust](https://faustjs.org/guide/how-to-use-apollo-in-faust) with [WPGraphQL Smart Cache](https://wordpress.org/plugins/wpgraphql-smart-cache/) (this hashes the queries into a consistently sized query ID, so you'll never run into queries being too large). This is the best of both worlds as you are still using `GET` requests for queries but you are no longer susceptible to URLs being too long.
> * Change the WPGraphQL requests back to `POST` requests [using the `useGETForQueries` config toggle in Faust](https://faustjs.org/guide/how-to-use-apollo-in-faust#changing-the-desired-http-method-for-your-graphql-requests)
> * talk to your hosting provider/modify your server to increase the max URL length
> * Decrease the query size by only requesting what is needed, etc.

Hey @blakewilson I got error 414 in my project and I used way 1 as you instructed here. I enabled `usePersistedQueries: true,` and created a plugin like this: https://github.com/wp-graphql/wpgraphql.com/blob/master/src/plugins/PersistedQueriesPlugin.js.

After that the 414 error is gone. However, one problem occurs is that it is not possible to use `getApolloAuthClient() `inside client queries as usual.
For example query get `Viewer `and it doesn't work.

Thanks in advance and I would greatly appreciate any help.
