### ISSUE TITLE
Bug:401 Unauthorized status in Chrome Log

### ISSUE THREAD

**Issue by nikoids** [wpengine/faustjs#1657]
When the user is not authorized, 401 status appears in the logs every time; after the user is authorized, this status disappears.
How can I prevent the 401 status from being shown to visitors in console.logs?

**Comment by OthyTenk** [comment]
Yes. Also, it affected my performance issues to me.
<img width="1263" alt="Screenshot 2023-11-19 at 17 27 20" src="https://github.com/wpengine/faustjs/assets/34827155/6c20bb50-4f7b-4f9e-b900-edd24f2a920e">

**Comment by theodesp** [comment]
Hey @OthyTenk and @nikoids . Those errors you are seing are originated from the Browser and the framework doesn't control this API nor does it emit this kind of messages. 

This is because the HTTP response has failed with a 401.

**Comment by mindctrl** [comment]
Noting that on faustjs.org, a 401 can be seen on every page load when logged out.

Related: when logged in on faustjs.org, two requests are made to `/api/faust/auth/token`. Of course they respond with 200 since I'm logged in, but it's two calls nonetheless.

**Comment by josephfusco** [comment]
I am currently experiencing the same issue 401 response on every page load made to `/api/faust/auth/token`.

<img width="1395" alt="Screenshot 2024-01-10 at 4 56 13 PM" src="https://github.com/wpengine/faustjs/assets/6676674/7973334c-6d46-42d0-b15c-6f177ff005a0">

Note that setting `experimentalToolbar: true` in `faust.config.js` will exhibit similar behavior due to the current implementation of the toolbar being client side.

This issue appeared after updating to the following canary versions:
```json
    "@faustwp/cli": "^0.0.0-20231205203747",
    "@faustwp/core": "^0.0.0-20240109203741",
```

**Comment by josephfusco** [comment]
The behavior reported yesterday can be observed using [today's release](https://github.com/wpengine/faustjs/pull/1672).

package.json
```json
    "@faustwp/cli": "^2.0.0",
    "@faustwp/core": "^2.0.0",
```

faust.config.js
```js
experimentalToolbar: false
```

Note the 401 issue was not observed in the last versions used.

**Comment by mindctrl** [comment]
This is fixed in https://github.com/wpengine/faustjs/pull/1724 and is going out for release within the next few minutes.

**Comment by jan-clockworkwp** [comment]
I can confirm that on the canary packages: 

```
    "@faustwp/cli": "^0.0.0-20231205203747",
    "@faustwp/core": "^0.0.0-20240129203730",
```

and with 

`experimentalToolbar: true,`

on localhost setup `accessToken.js` file still throws `401 (Unauthorized)` console.log error. When `experimentalToobar` feature is set to `false`, no error is thrown. Is this expected behaviour? Or there is improvement planned for `experimentalToolbar` feature?

**Comment by jan-clockworkwp** [comment]
Probably worth mentioning that there is as well Apollo Client error logged in the console, when `experimentalToolbar: true` and user is logged in. Basically when the ` 401 (Unauthorized)` is not thrown, then the Apollo one is. According to [Apollo error message](https://www.apollographql.com/docs/react/errors/#%7B%22version%22%3A%223.8.10%22%2C%22message%22%3A14%2C%22args%22%3A%5B%22viewer%22%2C%22RootQuery%22%2C%22either%20ensure%20all%20objects%20of%20type%20User%20have%20an%20ID%20or%20a%20custom%20merge%20function%2C%20or%20%22%2C%22RootQuery.viewer%22%2C%22%7B%5Cn%20%20%5C%22__typename%5C%22%3A%20%5C%22User%5C%22%2C%5Cn%20%20%5C%22shouldShowFaustToolbar%5C%22%3A%20true%5Cn%7D%22%2C%22%7B%5Cn%20%20%5C%22__ref%5C%22%3A%20%5C%22User%3AdXNlcjox%5C%22%5Cn%7D%22%5D%7D) seems like it can be related to missing `ID` on queried data. I have tried it with `"@apollo/client": "^3.9.2",` and `"@apollo/client": "^3.6.6",` versions.
